config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post '/boards/:id/memberships/' => 'memberships#create', as: :memberships_create
  put '/boards/:id/members/:user_id/admin' => 'memberships#admin', as: :add_admin_rights
  
  resources :boards do
    # resources :memberships, only: %i[create]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :board
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :board_id
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable, :validatable,
         :confirmable, :recoverable

  has_many :memberships, dependent: :destroy
  has_many :boards, through: :memberships
  validates :email, uniqueness: true

  has_many :administrated_boards, -> { where(memberships: {admin: true}) }, class_name: 'Board', 
  through: :memberships, source: :board

  scope :search, ->(email) { where('email LIKE ?', "%#{email}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :find_board!
  before_action :find_user!
  before_action :authorize!

  def create
    @board.users << @user
    flash[:success] = 'Membership Success'
  rescue ActiveRecord::RecordInvalid => e
    flash[:danger] = e.message
  end

  def admin
    @user.memberships.update(admin: true)
    if @user.memberships.empty?
      flash[:success] = 'Admin Success'
    else
      flash[:danger] = 'Admin Error'
    end
  end

  private

  def find_board!
    @board = Board.find(params[:id])
  end

  def find_user!
    @user = User.find(params[:user_id])
  end

  def authorize!
    unless current_user.administrated_boards.exists?(@board.id)
      render file: "public/401.html", status: :unauthorized
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.search(params[:search]).limit(10)

    respond_to do |foramt|
      foramt.json { render json: @users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.haml
%h1 Boards#index
%p Find me in app/views/boards/index.html.haml

app/views/boards/show.html.haml
= javascript_pack_tag 'auto', 'data-turbolinks-track': 'reload'

.container
    .row.justify-content-md-center
        .col-md-6
            .input-group.input-group-sm
                %input.form-control{"data-search" => "template-search", :tabindex => "0", :type => "text", id: "autoComplete"}/
                %input{type: "hidden", value: memberships_create_path(@board), id: "addMembershipURL"}
            %ul.list-group.search-list.show#show-users

#flash-box
    - flash.each do |name, message|
        .toast-container.toast-top-right#toast-container
            .toast.toast-error{"aria-live" => "assertive", :style => "display: block;"}
                .toast-title= name
                .toast-message= message

-# #flash-box.toast-container.toast-top-right
-#     .toast.toast-error{"aria-live": "assertive", style: "display: block;"}
-#         .toast.toast-error#flash-box
-#             - flash.each do |name, msg|
-#                 .toast-tile= name
-#                 .toast-message= msg

%h1 Board
%p= @board.title
%p= @board.description
%p= @board.public

#user-section
    - @board.users.each do |user|
        %p= user.email
        - unless user.administrated_boards.exists?(@board.id)
            = link_to 'Make Admin', add_admin_rights_path(id: @board.id, user_id: user.id), class: 'btn btn-primary', id: 'add_admin', method: :put


<script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@7.2.0/dist/js/autoComplete.min.js"></script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projector</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/membership/create.js.erb
console.log('Hello, World!');